<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR">
<title>Insert title here</title>
</head>
<body>
<!-- /* BOARD */
CREATE TABLE BOARD (
	NO NUMBER(5) NOT NULL, /* NO */
	NAME VARCHAR2(20), /* NAME */
	SUBJECT VARCHAR2(20), /* SUBJECT */
	PW VARCHAR2(20), /* PW */
	CONTENTS CLOB, /* CONTENTS */
	HIT NUMBER(4), /* HIT */
	REGDATE DATE, /* REGDATE */
	FILENAME VARCHAR2(50) /* FILENAME */
);

/* BOARDBEAN */
CREATE TABLE BOARDBEAN (
	NO NUMBER(5), /* NO */
	NAME VARCHAR2(20), /* NAME */
	SUBJECT VARCHAR2(20), /* SUBJECT */
	PW VARCHAR2(20), /* PW */
	CONTENTS CLOB, /* CONTENTS */
	HIT NUMBER(4), /* HIT */
	REGDATE DATE, /* REGDATE */
	FILENAME VARCHAR2(50) /* FILENAME */
);

/* CART */
CREATE TABLE CART (
	NO NUMBER(10) NOT NULL, /* NO */
	PRODUCTNAME VARCHAR2(20), /* PRODUCTNAME */
	PRODUCTORIGIN VARCHAR2(20), /* PRODUCTORIGIN */
	PRODUCTPRICE NUMBER(20), /* PRODUCTPRICE */
	PRODUCTCATEGORY VARCHAR2(20), /* PRODUCTCATEGORY */
	FILENAME VARCHAR2(20), /* FILENAME */
	REGDATE DATE, /* REGDATE */
	ID VARCHAR2(20) /* ID */
);

/* COMPANY */
CREATE TABLE COMPANY (
	ID VARCHAR2(20) NOT NULL, /* ID */
	PW VARCHAR2(20) NOT NULL, /* PW */
	NAME VARCHAR2(50) NOT NULL, /* NAME */
	COMPANYNUM VARCHAR2(20) NOT NULL, /* COMPANYNUM */
	IMG VARCHAR2(20) /* IMG */
);

CREATE UNIQUE INDEX PK_COMPANY
	ON COMPANY (
		ID ASC
	);

/* CUSTOMER */
CREATE TABLE CUSTOMER (
	CID VARCHAR2(20) NOT NULL, /* CID */
	CPW VARCHAR2(20) NOT NULL, /* CPW */
	CNAME VARCHAR2(20) NOT NULL, /* CNAME */
	CGENDER VARCHAR2(5) NOT NULL, /* CGENDER */
	CPHONE VARCHAR2(20) NOT NULL, /* CPHONE */
	CADDRESS CLOB NOT NULL, /* CADDRESS */
	CEMAIL VARCHAR2(50) NOT NULL, /* CEMAIL */
	CBIRTH DATE NOT NULL, /* CBIRTH */
	CPOINT NUMBER(5), /* CPOINT */
	CLEVEL VARCHAR2(20), /* CLEVEL */
	CJOINDATE DATE NOT NULL /* CJOINDATE */
);

CREATE UNIQUE INDEX PK_CUSTOMER
	ON CUSTOMER (
		CID ASC
	);

/* MEMBER */
CREATE TABLE MEMBER (
	NO NUMBER(5) NOT NULL, /* NO */
	ID VARCHAR2(20) NOT NULL, /* ID */
	PW VARCHAR2(20) NOT NULL, /* PW */
	NAME VARCHAR2(20) NOT NULL, /* NAME */
	PHONE VARCHAR2(30) NOT NULL, /* PHONE */
	ADDR VARCHAR2(255) NOT NULL, /* ADDR */
	GRADE VARCHAR2(30) NOT NULL, /* GRADE */
	POINT NUMBER(10) NOT NULL, /* POINT */
	JOINDATE DATE NOT NULL /* JOINDATE */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		NO ASC
	);

/* QNABOARD */
CREATE TABLE QNABOARD (
	NO NUMBER(5) NOT NULL, /* NO */
	CATEGORY VARCHAR2(30), /* CATEGORY */
	TITLE VARCHAR2(20), /* TITLE */
	WRITER VARCHAR2(20), /* WRITER */
	CONTENTS CLOB, /* CONTENTS */
	REGDATE DATE, /* REGDATE */
	FILENAME VARCHAR2(30), /* FILENAME */
	PASSWORD NUMBER(4), /* PASSWORD */
	PNUM NUMBER(5) /* PNUM */
);

CREATE UNIQUE INDEX QNABOARD_NO_PK
	ON QNABOARD (
		NO ASC
	);

/* REVIEW */
CREATE TABLE REVIEW (
	RNO NUMBER(10), /* RNO */
	ID VARCHAR2(40), /* ID */
	FILENAME VARCHAR2(40), /* FILENAME */
	CONTENTS CLOB, /* CONTENTS */
	REGDATE DATE, /* REGDATE */
	PKNO NUMBER(10), /* PKNO */
	REF NUMBER(10), /* REF */
	PNUM NUMBER(10) /* PNUM */
);

/* ZIPCODE */
CREATE TABLE ZIPCODE (
	ZIPCODE VARCHAR2(100), /* ZIPCODE */
	SIDO VARCHAR2(100), /* SIDO */
	GUGUN VARCHAR2(100), /* GUGUN */
	DONG VARCHAR2(100), /* DONG */
	BUNJI VARCHAR2(100), /* BUNJI */
	SEQ VARCHAR2(100) /* SEQ */
); -->
</body>
</html>